# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aoc2md < Formula
  desc "The aoc2md tool to generate project setup 🎄"
  homepage "https://kevinrobayna.com "
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinrobayna/aoc2md/releases/download/v0.1.3/aoc2md_Darwin_arm64.tar.gz"
      sha256 "3ff6d599596a14828ae23209e550b98131ae5c0b21df22c4409359c41a58d3af"

      def install
        bin.install "aoc2md"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kevinrobayna/aoc2md/releases/download/v0.1.3/aoc2md_Darwin_x86_64.tar.gz"
      sha256 "88806691fe7f9f79bb7cf9920d74f8bc04aa2cfb3c8eab986c87c970e3633cc4"

      def install
        bin.install "aoc2md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinrobayna/aoc2md/releases/download/v0.1.3/aoc2md_Linux_arm64.tar.gz"
      sha256 "c4f9fc8822f4007c9932f48abc1f696717f3028094fd2ea52b631fc08b8f4ada"

      def install
        bin.install "aoc2md"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kevinrobayna/aoc2md/releases/download/v0.1.3/aoc2md_Linux_x86_64.tar.gz"
      sha256 "62eddad851345024d8db6a0072115fbe08a78071e30d8bd90a60312ad1ce6a9b"

      def install
        bin.install "aoc2md"
      end
    end
  end
end
