# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeowner" do
  name "codeowner"
  desc "A CLI tool for working with CODEOWNERS files"
  homepage "https://github.com/kevinrobayna/codeowner"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeowner"

  on_macos do
    on_intel do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_darwin_amd64.tar.gz"
      sha256 "893a611d4ba36ce859128d48456b064a46bb1a128f23e9cf581e49c447c547a2"
    end
    on_arm do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_darwin_arm64.tar.gz"
      sha256 "64efd5f8aa86405e0d86864f0d1493edeb81917ee1178a45988bbc9c27a3f70f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_linux_amd64.tar.gz"
      sha256 "a9199b51c30d287cbbb56a2c83a28181fb4669bed3f9aa20eab0e82b38282409"
    end
    on_arm do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_linux_arm64.tar.gz"
      sha256 "5deb06d4d71ca3d09a8f16d5c5c488960cdb2734afc2c001f36cc9127fba5b7c"
    end
  end

  # No zap stanza required
end
