# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeowner" do
  name "codeowner"
  desc "A CLI tool for working with CODEOWNERS files"
  homepage "https://github.com/kevinrobayna/codeowner"
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeowner"

  on_macos do
    on_intel do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_darwin_amd64.tar.gz"
      sha256 "3265fe96343e3876fe47d55332631bc9d803793b37de83ed036d9a6747238a59"
    end
    on_arm do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_darwin_arm64.tar.gz"
      sha256 "390f0c63ca2cde0b7db7c348fff020ad38f1586503c3919fd3c6f61b66b36986"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_linux_amd64.tar.gz"
      sha256 "b892f34e52272e017b741567b5e13e208d58f785f3143d6ff8714b622fd595cc"
    end
    on_arm do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_linux_arm64.tar.gz"
      sha256 "3bc8b3bce6e66c79113bcd4cab423133efefe9a19995a8e183a06c4f80696666"
    end
  end

  # No zap stanza required
end
