# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeowner" do
  name "codeowner"
  desc "A CLI tool for working with CODEOWNERS files"
  homepage "https://github.com/kevinrobayna/codeowner"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeowner"

  on_macos do
    on_intel do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_darwin_amd64.tar.gz"
      sha256 "f9bae6280f1030c35712699c94d8209f971296d4715a8c622ec2c4beb60565ee"
    end
    on_arm do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_darwin_arm64.tar.gz"
      sha256 "fbc0fda6fc48f97d2fdb6d68abc86e6938d0a41d862704efd6d300630c86953a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_linux_amd64.tar.gz"
      sha256 "25ad256b322f2ba85dcfd1c01ceb6e171f1fe4229a15c644784696c57e9da226"
    end
    on_arm do
      url "https://github.com/kevinrobayna/codeowner/releases/download/v#{version}/codeowner_#{version}_linux_arm64.tar.gz"
      sha256 "e91a259bb521d1c61757bae97c8d2079f956bbde130c71486698593d72c853c5"
    end
  end

  # No zap stanza required
end
