# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeowner < Formula
  desc "A CLI tool for working with CODEOWNERS files"
  homepage "https://github.com/kevinrobayna/codeowner"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kevinrobayna/codeowner/releases/download/v0.2.1/codeowner_0.2.1_darwin_amd64.tar.gz"
      sha256 "d1b542e2bb60d0e33776bf6d8e594981dec6f634d97185aa018ddcc9d05fc212"

      define_method(:install) do
        bin.install "codeowner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kevinrobayna/codeowner/releases/download/v0.2.1/codeowner_0.2.1_darwin_arm64.tar.gz"
      sha256 "02bebab8ba9237cba77a65df4a14216387f3d60a51f4e2d5d5309224ba5548fe"

      define_method(:install) do
        bin.install "codeowner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinrobayna/codeowner/releases/download/v0.2.1/codeowner_0.2.1_linux_amd64.tar.gz"
      sha256 "d74066b54f1af87355073d2b133e32160d64dc3a34436527cc2225eef9749718"
      define_method(:install) do
        bin.install "codeowner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinrobayna/codeowner/releases/download/v0.2.1/codeowner_0.2.1_linux_arm64.tar.gz"
      sha256 "ac3050a45b8f5758f93d1e6b9c0db5d7c2e41cc2034fbc78aeb769886c3b1a18"
      define_method(:install) do
        bin.install "codeowner"
      end
    end
  end
end
