# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeowner < Formula
  desc "A CLI tool for working with CODEOWNERS files"
  homepage "https://github.com/kevinrobayna/codeowner"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kevinrobayna/codeowner/releases/download/v0.1.1/codeowner_0.1.1_darwin_amd64.tar.gz"
      sha256 "005cbfc2373204caf0d47730b597edcbfe186a16e43deaa650527767bbeb86b0"

      define_method(:install) do
        bin.install "codeowner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kevinrobayna/codeowner/releases/download/v0.1.1/codeowner_0.1.1_darwin_arm64.tar.gz"
      sha256 "10f4a94f59af0b68e4271f067ed7be0ad0b2cf530505cba93b2dcdedf60d9340"

      define_method(:install) do
        bin.install "codeowner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinrobayna/codeowner/releases/download/v0.1.1/codeowner_0.1.1_linux_amd64.tar.gz"
      sha256 "71ecf2fb1bae3afb9147e2d9893c1211556a5153f49c111f424f3ebba8257242"
      define_method(:install) do
        bin.install "codeowner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinrobayna/codeowner/releases/download/v0.1.1/codeowner_0.1.1_linux_arm64.tar.gz"
      sha256 "39291d2547876c9fa2d3b39ac6a64c878fea45696059eb27a87e61b152237cb7"
      define_method(:install) do
        bin.install "codeowner"
      end
    end
  end

  test do
    system "#{bin}/codeowner", "version"
  end
end
